logging:
  config: classpath:log4j2.yml
#  config: classpath:log4j2-prod.yml

server:
  port: 9052
spring:
  application:
    name: creator
  datasource:
    name: creator
    creatoraccount:
    url: jdbc:mysql://127.0.0.1:3306/account?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: root
    password: 123456

    # \u963F\u91CC\u5DF4\u5DF4druid\u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # \u65F6\u533A+8\u5C0F\u65F6
  jackson:
    time-zone: GMT+8


mybatis:
  mapperLocations: classpath:mapper/*.xml



