logging:
  config: classpath:log4j2.yml

server:
  port: 9999

spring:
  application:
    name: cube-configcenter
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:conf/

eureka:
  client:
    serviceUrl:
      defaultZone: http://cubespace:CubeSpace.2015@localhost:20000/eureka/