logging:
  config: classpath:log4j2.yml

server:
  port: 20000

spring:
  application:
    name: cube-server

  security:
    user:
      password: CubeSpace.2015
      name: cubespace

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否注册自身到eureka服务器 false
    #是否从eureka上获取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
