logging:
  config: classpath:log4j2.yml

server:
  port: 10000

spring:
  application:
    name: gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 30MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    timeout: 1000
#    jedis:
#      pool:
#        max-active: 10
#        min-idle: 0
#        max-idle: 8
#        max-wait: -1
#    password: icubespace.com


eureka:
#  instance:
#    prefer-ip-address: true
#    status-page-url-path: /actuator/info
#    health-check-url: actuator/health
  client:
    serviceUrl:
      defaultZone: http://cubespace:CubeSpace.2015@localhost:20000/eureka/
    register-with-eureka: true
    fetch-registry: true

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 30000
zuul:
  host:
    connect-timeout-millis: 300000
    socket-timeout-millis: 300000
  routes:
    user:
      path: /user/**
      service-id: USER-CONSUMER
    gx:
      path: /gx/**
      service-id: GXCONSUMER
    creator:
      path: /creator/**
      service-id: CREATOR-CONSUMER

  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken

cubespace:
  whileUrls:
    - /public/
    - /orgType
    - /api/care/

