logging:
  config: classpath:log4j2.yml

server:
  port: 9005
spring:
  application:
    name: CREATOR-CONSUMER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    service-url:
      defaultZone: http://cubespace:CubeSpace.2015@localhost:20000/eureka/
    register-with-eureka: true
    fetch-registry: true

cubespace:
  uploadTempPath: /Volumes/MyDisk/temp/
  restReadTimeout: 30000
  restConnectTimeout: 30000


