#默认使用配置
logging:
  config: classpath:log4j2-prod.yml


server:
  port: 10203
spring:
  application:
    name: kilobeesystem

  datasource:
    name: kilobeesystem
    url: jdbc:mysql://127.0.0.1:3306/gaoxun?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123qweQWE++
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

eureka:
  client:
    service-url:
      defaultZone: http://cubespace:CubeSpace.2015@localhost:20000/eureka/
    register-with-eureka: true
    fetch-registry: true




#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.icubespace.projects.kilobeesystem.entity
  mapperLocations: classpath:mybatis/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql