#默认使用配置
logging:
  config: classpath:log4j2.yml

server:
  port: 10205
spring:
  application:
    name: pushsystem

  datasource:
    name: pushsystem
    url: jdbc:mysql://localhost:3306/cloud-push?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123.com
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

eureka:
  client:
    service-url:
      defaultZone: http://cubespace:CubeSpace.2015@localhost:20000/eureka/




#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.icubespace.projects.pushsystem.entity
  mapperLocations: classpath:mybatis/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql