logging:
  config: classpath:log4j2.yml


server:
  port: 10209
spring:
  application:
    name: resourcesystem
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 30MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录

  datasource:
    name: resourcesystem
    url: jdbc:mysql://192.168.1.19:3306/cloud-gx?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: cubespace
    password: landXzMQ+2017
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20



eureka:
  client:
    service-url:
      defaultZone: http://cubespace:CubeSpace.2015@localhost:20000/eureka/
    register-with-eureka: true
    fetch-registry: true


cubespace:
  localFilePath: /mnt/cloud/files/


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.icubespace.projects.tasksystem.entity
  mapperLocations:
    - classpath:mybatis/*.xml
    - classpath:mybatis/org/*.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql