#默认使用配置
logging:
  config: classpath:log4j2-prod.yml


server:
  port: 10201
spring:
  application:
    name: usersystem

  datasource:
    name: usersystem
    url: jdbc:mysql://rm-wz97nf9952cnf465m.mysql.rds.aliyuncs.com:3306/cloud-gx?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: cubespace
    password: landXzMQ&2017
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        min-idle: 0
        max-idle: 8
        max-wait: -1
    password: icubespace.com

  cloud:
    stream:
      rabbit:
        bindings:
          orgCourseOutput:
            destination: queue.org.course
            binder: local_rabbit
          orgClassOutput:
            destination: queue.org.class
            binder: local_rabbit
        binders:
          local_rabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: cubespace
                  password: cubespace2015.com
                  virtual-host: /

eureka:
  client:
    service-url:
      defaultZone: http://cubespace:CubeSpace.2015@localhost:20000/eureka/
    register-with-eureka: true
    fetch-registry: true




#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.icubespace.projects.usersystem.entity
  mapperLocations:
    - classpath:mybatis/*.xml
    - classpath:mybatis/org/*.xml
    - classpath:mybatis/train/*.xml
    - classpath:mybatis/task/*.xml
    - classpath:mybatis/query/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql