logging:
  config: classpath:log4j2.yml
#  config: classpath:log4j2-prod.yml

server:
  port: 9051
spring:
  application:
    name: creator
  mvc:
    static-path-pattern: /static/**
  datasource:
    name: creator
    creatoraccount:
      url: jdbc:mysql://127.0.0.1:3306/account?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
      username: root
      password: 123456

      # 阿里巴巴druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

    creatorcourse:
      url: jdbc:mysql://127.0.0.1:3306/course_dj?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
      username: root
      password: 123456

      # 阿里巴巴druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

    creatorcourse1:
      url: jdbc:mysql://127.0.0.1:3306/course_cp?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
      username: root
      password: 123456

      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  # 时区+8小时
  jackson:
    time-zone: GMT+8

# mybatis mapper.xml 文件配置路径
#mybatis:
#  mapperLocations: classpath:mapper/*/*.xml

# 文件上传路径
creator:
#  uploadPath: /mnt/vue/creator/course/static/
#  uploadPath: D:\tomcat\apache-tomcat-8.5.38\webapps\course\static\
  uploadPath: D:\javatools\tomcat\apache-tomcat-8.5.40\webapps\creator\
  downloadPath: 192.168.2.223:8080\creator\

